server:
  port: 8080
spring:
  datasource:
    name: test
    url: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
      filters: stat
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 6000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: LEGACYHTML5
    suffix: .html
    prefix: classpath:/templates/
  devtools:
    restart:
      enabled: true
      exclude: templates

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.itea.model

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  returnPageInfo: check

#logging:
#  level: debug
